# -*- coding: utf-8 -*-
"""exp4stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOmTaAk0F6hCXhFEDcCBOCDxMcX3rVUb
"""

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/sample_data/diabetes.csv')

# Display the first 5 rows of the DataFrame
print("First 5 rows of the dataset:")
display(df.head())

# Display basic information about the DataFrame
print("\nDataFrame Info:")
df.info()

# Display descriptive statistics of the DataFrame
print("\nDescriptive Statistics:")
display(df.describe())

"""The dataset contains several variables related to patient health, including: `Pregnancies`, `Glucose`, `BloodPressure`, `SkinThickness`, `Insulin`, `BMI`, `DiabetesPedigreeFunction`, `Age`, and `Outcome` (which is the target variable, indicating diabetes).

Before proceeding with calculations, it's important to handle any missing values, which often appear as zeros in this dataset for variables like `Glucose`, `BloodPressure`, `SkinThickness`, `Insulin`, and `BMI`, where a zero value is physiologically impossible. We will replace these zeros with `NaN` and then decide on an imputation strategy, such as replacing them with the median.
"""

# Replace 0 values with NaN for relevant columns where 0 is not a valid measurement
columns_with_zeros_as_nan = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for col in columns_with_zeros_as_nan:
    df[col] = df[col].replace(0, np.nan)

# Check for missing values after replacement
print("Missing values after replacing 0s with NaN:")
display(df.isnull().sum())

# Impute missing values with the median of each column
for col in columns_with_zeros_as_nan:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

# Verify that there are no more missing values
print("\nMissing values after median imputation:")
display(df.isnull().sum())

print("\nFirst 5 rows after cleaning:")
display(df.head())

"""### Point Estimates and Confidence Intervals

Now, let's calculate some point estimates for selected variables. We'll determine the sample mean for `Glucose` and the sample proportion for `Outcome` (diabetes prevalence). Following that, we'll construct 95% confidence intervals for these population parameters.
"""

# 1. Point Estimate: Sample Mean of Glucose
glucose_mean = df['Glucose'].mean()
print(f"Sample Mean of Glucose: {glucose_mean:.2f}")

# 2. Confidence Interval for Population Mean of Glucose (using t-distribution for small sample or unknown population std)
glucose_std = df['Glucose'].std()
glucose_count = df['Glucose'].count()
glucose_sem = glucose_std / np.sqrt(glucose_count) # Standard Error of the Mean

# For a 95% confidence interval, alpha = 0.05, so alpha/2 = 0.025. Degrees of freedom = count - 1
confidence_level = 0.95
alpha = 1 - confidence_level
t_critical = stats.t.ppf(1 - alpha/2, df=glucose_count - 1)

margin_of_error_glucose = t_critical * glucose_sem
confidence_interval_glucose = (glucose_mean - margin_of_error_glucose, glucose_mean + margin_of_error_glucose)
print(f"95% Confidence Interval for Population Mean Glucose: ({confidence_interval_glucose[0]:.2f}, {confidence_interval_glucose[1]:.2f})")

# 3. Point Estimate: Sample Proportion of Diabetes (Outcome == 1)
diabetes_proportion = df['Outcome'].mean() # Since Outcome is 0 or 1, the mean is the proportion
print(f"\nSample Proportion of Diabetes: {diabetes_proportion:.3f}")

# 4. Confidence Interval for Population Proportion of Diabetes
# Using the Wald method for proportion confidence interval
# Standard Error of Proportion = sqrt(p * (1 - p) / n)
n = len(df)
std_err_proportion = np.sqrt(diabetes_proportion * (1 - diabetes_proportion) / n)

# For a 95% confidence interval, z_critical for a two-tailed test is 1.96
z_critical = stats.norm.ppf(1 - alpha/2) # For large samples, normal approximation is often used

margin_of_error_proportion = z_critical * std_err_proportion
confidence_interval_proportion = (diabetes_proportion - margin_of_error_proportion, diabetes_proportion + margin_of_error_proportion)
print(f"95% Confidence Interval for Population Proportion of Diabetes: ({confidence_interval_proportion[0]:.3f}, {confidence_interval_proportion[1]:.3f})")

"""### Hypothesis Testing: Two-Sample t-test

**Research Question:** Is there a significant difference in the mean glucose levels between individuals with diabetes and those without diabetes?

**Hypotheses:**
*   **Null Hypothesis (H0):** There is no significant difference in the mean glucose levels between diabetic and non-diabetic individuals (μ_diabetic = μ_non-diabetic).
*   **Alternative Hypothesis (H1):** There is a significant difference in the mean glucose levels between diabetic and non-diabetic individuals (μ_diabetic ≠ μ_non-diabetic).

**Significance Level (α):** 0.05
"""

# Separate data into two groups based on 'Outcome'
diabetic_glucose = df[df['Outcome'] == 1]['Glucose']
non_diabetic_glucose = df[df['Outcome'] == 0]['Glucose']

# Perform independent two-sample t-test
# We assume unequal variances (Welch's t-test) as a safer default, though an F-test could check for equality
t_statistic, p_value = stats.ttest_ind(diabetic_glucose, non_diabetic_glucose, equal_var=False)

print(f"Two-Sample t-test for Glucose Levels:\n")
print(f"  Mean Glucose (Diabetic): {diabetic_glucose.mean():.2f}")
print(f"  Mean Glucose (Non-Diabetic): {non_diabetic_glucose.mean():.2f}")
print(f"  t-statistic: {t_statistic:.2f}")
print(f"  p-value: {p_value:.3f}")

# Compare p-value with significance level
significance_level = 0.05
print(f"\nSignificance Level (α): {significance_level}")

if p_value < significance_level:
    print("Decision: Reject the null hypothesis.")
    print("Interpretation: There is a statistically significant difference in mean glucose levels between individuals with diabetes and those without diabetes.")
elif p_value > significance_level:
    print("Decision: Fail to reject the null hypothesis.")
    print("Interpretation: There is no statistically significant difference in mean glucose levels between individuals with diabetes and those without diabetes.")

"""### Hypothesis Testing: Chi-square Test

To apply the Chi-square test, we first need to create categorical variables. Let's create `AgeGroup` from the `Age` column.

**Research Question:** Is there a significant association between `AgeGroup` and `Outcome` (diabetes status)?

**Hypotheses:**
*   **Null Hypothesis (H0):** There is no association between `AgeGroup` and `Outcome` (they are independent).
*   **Alternative Hypothesis (H1):** There is an association between `AgeGroup` and `Outcome` (they are dependent).

**Significance Level (α):** 0.05
"""

# Create Age Groups
bins = [20, 30, 40, 50, 60, 70, 80, 90]
labels = ['20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80-89']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

# Create a contingency table
contingency_table = pd.crosstab(df['AgeGroup'], df['Outcome'])
print("Contingency Table (AgeGroup vs. Outcome):\n")
display(contingency_table)

# Perform Chi-square test of independence
chi2_statistic, p_value_chi2, dof, expected_freq = stats.chi2_contingency(contingency_table)

print(f"\nChi-square Test of Independence (AgeGroup vs. Outcome):\n")
print(f"  Chi-square statistic: {chi2_statistic:.2f}")
print(f"  p-value: {p_value_chi2:.3f}")
print(f"  Degrees of freedom: {dof}")

# Compare p-value with significance level
significance_level = 0.05
print(f"\nSignificance Level (α): {significance_level}")

if p_value_chi2 < significance_level:
    print("Decision: Reject the null hypothesis.")
    print("Interpretation: There is a statistically significant association between age group and diabetes status.")
elif p_value_chi2 > significance_level:
    print("Decision: Fail to reject the null hypothesis.")
    print("Interpretation: There is no statistically significant association between age group and diabetes status.")