# -*- coding: utf-8 -*-
"""exp1stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tja2WHk0nFOUcqGPwonUAH67Zrj2p426

# 1. Import Libraries and Load Dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/sample_data/diabetes.csv")

"""# 2. Data Inspection and Variable Classification"""

print("=== DATASET DIMENSIONS ===")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}\n")

print("=== SAMPLE RECORDS ===")
print(df.head(), "\n")

print("\n--- Class Distribution ---")
print(df['Outcome'].value_counts(normalize=True))

print("=== DATA TYPES & MISSING VALUES ===")
print(df.info(), "\n")

"""# 3. Statistical Summary"""

print("=== STATISTICAL SUMMARY ===")
print(df.describe(), "\n")

"""# 4. Checking for missing or Invalid Values"""

invalid_zero_cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
hidden_missing = (df[invalid_zero_cols] == 0).sum()
print(hidden_missing)

"""# 5. Raw Feature Distribution"""

plt.figure(figsize=(15, 10))
plt.suptitle("1. Raw Feature Distributions (Notice Artificial Spikes at 0)", fontsize=16, fontweight='bold')

for i, col in enumerate(df[:-1], 1):
    plt.subplot(3, 3, i)
    sns.histplot(data=df, x=col, hue='Outcome', kde=True, multiple='stack', palette='coolwarm')
    plt.title(f'{col} Trend')
    plt.xlabel('')

plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 12))
plt.suptitle("2. Raw Distribution of uncleaned individual Columns", fontsize=16, fontweight='bold')

for i, col in enumerate(df.columns, 1):
    plt.subplot(3, 3, i)
    sns.histplot(data=df, x=col, kde=True, color='royalblue')
    plt.title(f'{col} Distribution')
    plt.xlabel('')

plt.tight_layout()
plt.show()

"""# 6. Outlier Detection"""

plt.figure(figsize=(15, 12))
plt.suptitle("Raw Data Boxplots (Notice Zeros as False Low Outliers)", fontsize=16, fontweight='bold')

for i, col in enumerate(df[:-1], 1):
    plt.subplot(3, 3, i)
    sns.boxplot(data=df, x='Outcome', y=col, hue='Outcome', palette='Set2', legend=False)
    plt.title(f'Raw {col} Range')
    plt.xlabel('Outcome (0=Healthy, 1=Diabetic)')

plt.tight_layout()
plt.show()

plt.figure(figsize=(12,8))
sns.boxplot(data=df)
plt.title('Outlier Detection')
plt.xticks(rotation=90)
plt.show()

"""# 7. Feature Relationships and Linear Relations"""

plt.figure(figsize=(10, 8))
correlation_matrix = df.corr()

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, vmin=-1, vmax=1)
plt.title("3. Feature Correlation Matrix (Raw Data)", fontsize=14, fontweight='bold')
plt.show()

