# -*- coding: utf-8 -*-
"""exp3stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kipc5BNCrmpUTtgutUjKe-fM3XrLC60r

### 1. Load the Pima Indians Diabetes Dataset
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from scipy.spatial.distance import euclidean, cityblock, cosine

# Load the dataset from sample_data
df = pd.read_csv('/content/sample_data/diabetes.csv')
display(df.head())

"""### 2. Identify and Handle Missing/Invalid Values
In this dataset, columns like Glucose, BloodPressure, SkinThickness, Insulin, and BMI should not have zero values. We will replace zeros with NaN and then impute them using the median.
"""

cols_with_zeros = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

# Replace 0 with NaN
df[cols_with_zeros] = df[cols_with_zeros].replace(0, np.nan)

# Check count of missing values
print("Missing values per column:")
print(df.isnull().sum())

# Impute missing values with median
for col in cols_with_zeros:
    df[col] = df[col].fillna(df[col].median())

print("\nMissing values after imputation:")
print(df.isnull().sum())

"""### 3. Correlation Analysis
We'll calculate the correlation matrix and visualize it with a heatmap.
"""

corr_matrix = df.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix Heatmap')
plt.show()

"""### 4. Distance Measures
Calculating distances between the first two observations.
"""

obs1 = df.iloc[0, :-1].values
obs2 = df.iloc[1, :-1].values

print(f"Euclidean Distance: {euclidean(obs1, obs2):.4f}")
print(f"Manhattan (Cityblock) Distance: {cityblock(obs1, obs2):.4f}")
print(f"Cosine Distance: {cosine(obs1, obs2):.4f}")

"""### 5. Normalization
Scaling features to a range [0, 1] and comparing the data distributions.
"""

scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df.drop(columns=['Outcome'])), columns=df.columns[:-1])

print("Data Before Normalization (Head):")
display(df.drop(columns=['Outcome']).head(3))

print("\nData After Normalization (Head):")
display(df_normalized.head(3))

"""### 6. Standardization (Z-score Scaling)
Standardization transforms the data to have a mean of 0 and a standard deviation of 1. Let's apply it using `StandardScaler`.
"""

from sklearn.preprocessing import StandardScaler

scaler_std = StandardScaler()
df_standardized = pd.DataFrame(scaler_std.fit_transform(df.drop(columns=['Outcome'])), columns=df.columns[:-1])

print("Data After Standardization (Mean ≈ 0, Std ≈ 1):")
display(df_standardized.head(3))

# Verify mean and std
print("\nMean of standardized Glucose:", round(df_standardized['Glucose'].mean(), 2))
print("Std of standardized Glucose:", round(df_standardized['Glucose'].std(), 2))

"""### Comparison of Normalization vs Standardization
Below we compare the first row of data under both techniques to see how they differ numerically.
"""

comparison_df = pd.DataFrame({
    'Original': df.iloc[0, :-1],
    'Normalized (0 to 1)': df_normalized.iloc[0],
    'Standardized (Mean=0)': df_standardized.iloc[0]
})

display(comparison_df)